<GridLayout>
    cols:2
    Label:
        font_size: 30
        text:"Заказ"
        color:0.6,0.9,1,0.9
        background_color:1,0.1,0.7,0.9
    TextInput:
        font_size: 30
        background_color:0.8,0.8,0.5,1
    Label:
        font_size: 30
        text:"Адрес"
        color:0.6,0.9,1,0.9
        background_color:1,0.1,0.7,0.9
    TextInput:
        font_size: 30
        background_color:0.8,0.8,0.5,1
    Label:
        font_size: 30
        text:"Телефон"
        color:0.6,0.9,1,0.9
        background_color:0.5,1,1,1
    TextInput:
        font_size: 30
        background_color:0.8,0.8,0.5,1
    Button:
        font_size:20
        text:"Подтвердить"
        width:100
        color:100,15,40
        background_color:0.2,0.5,0.9,1
